services:
  nginx-gateway:
    image: nginx:alpine3.20-perl
    container_name: nginx-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # undercover 配置文件
      - ./app/undercover/undercover.conf:/etc/nginx/conf.d/:ro # 覆盖 default.conf
      - ./app/undercover/cert:/etc/nginx/cert/undercover:ro
    restart: unless-stopped
